import React from 'react';
import { Info } from 'lucide-react';

export const DisclaimerCard: React.FC = () => {
  return (
    <footer className="bg-[#111827]/70 border border-slate-800/60 rounded-2xl p-4 sm:p-5 text-center">
      <div className="flex items-start justify-center gap-2.5">
        <Info className="w-4 h-4 text-slate-500 shrink-0 mt-0.5" />
        <p className="text-slate-400 text-xs leading-relaxed max-w-3xl text-left">
          Dealhunter X is for education only. Not financial advice. Trade ideas are generated by AI from public sources and may be wrong. The tagline describes you can delegate tasks, but not responsibility.
        </p>
      </div>
    </footer>
  );
};
